### ISSUE TITLE
RuntimeError: __class__ not set defining 'BatchBeam' as <class 'utils.beam_search.BatchBeam'>. Was __classcell__ propagated to type.__new__?

### ISSUE THREAD

**Issue by Bxliang868** [adamslab-ub/CapAM-MRTA#1]
Traceback (most recent call last):
  File "run.py", line 12, in <module>
    from train import train_epoch, validate, get_inner_model
  File "/mnt/Data_1/gaokai/lbx/CA/train.py", line 10, in <module>
    from nets.attention_model import set_decode_type
  File "/mnt/Data_1/gaokai/lbx/CA/nets/attention_model.py", line 11, in <module>
    from utils.beam_search import CachedLookup
  File "/mnt/Data_1/gaokai/lbx/CA/utils/beam_search.py", line 54, in <module>
    class BatchBeam(NamedTuple):
RuntimeError: __class__ not set defining 'BatchBeam' as <class 'utils.beam_search.BatchBeam'>. Was __classcell__ propagated to type.__new__?

**Comment by OrangeJui321** [comment]
Using python=3.7

**Comment by timothyUcas** [comment]
class BatchBeam(NamedTuple) --> class BatchBeam: 
replace all the NamedTuple with the right, then the problem is solved!
